# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8132d738e5545f56b44f8dc39533c4bbd214ca975d8d2d5d60ae0fa7dc6826f2d4e3608bfa5600ab1f215aada6497c0d806348d13dfd186b3803c13f143562e9

test:
  secret_key_base: 4240e1d5c60c9cd1d6ac5a4ab3762427f1cf2c6793953db4c1aa9805a2ddb31ad5980063987d86b831cc32e0435915effec4d071c6ca33888465e35c8ac064f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
